//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeeDBEntities : DbContext
    {
        public EmployeeDBEntities()
            : base("name=EmployeeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int STP_DeleteEmployeeById(Nullable<int> empId)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DeleteEmployeeById", empIdParameter);
        }
    
        public virtual ObjectResult<STP_GetAllEmployees_Result> STP_GetAllEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetAllEmployees_Result>("STP_GetAllEmployees");
        }
    
        public virtual ObjectResult<STP_GetAllEmployeesSearch_Result> STP_GetAllEmployeesSearch(string input)
        {
            var inputParameter = input != null ?
                new ObjectParameter("input", input) :
                new ObjectParameter("input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_GetAllEmployeesSearch_Result>("STP_GetAllEmployeesSearch", inputParameter);
        }
    
        public virtual int STP_SaveEmployeeDetails(string empName, Nullable<int> age, Nullable<decimal> salary, string mStatus, string empLocation)
        {
            var empNameParameter = empName != null ?
                new ObjectParameter("EmpName", empName) :
                new ObjectParameter("EmpName", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(decimal));
    
            var mStatusParameter = mStatus != null ?
                new ObjectParameter("MStatus", mStatus) :
                new ObjectParameter("MStatus", typeof(string));
    
            var empLocationParameter = empLocation != null ?
                new ObjectParameter("EmpLocation", empLocation) :
                new ObjectParameter("EmpLocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_SaveEmployeeDetails", empNameParameter, ageParameter, salaryParameter, mStatusParameter, empLocationParameter);
        }
    
        public virtual int STP_UpdateEmployee(Nullable<int> empId, string empName, Nullable<int> age, Nullable<decimal> salary, string location, string mStatus)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var empNameParameter = empName != null ?
                new ObjectParameter("EmpName", empName) :
                new ObjectParameter("EmpName", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(decimal));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var mStatusParameter = mStatus != null ?
                new ObjectParameter("MStatus", mStatus) :
                new ObjectParameter("MStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_UpdateEmployee", empIdParameter, empNameParameter, ageParameter, salaryParameter, locationParameter, mStatusParameter);
        }
    }
}
